name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: firebase-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: List repo
        run: |
          pwd
          ls -la
          ls -la site || true

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ITI_SITE }}
          projectId: ittakesimagination-main
          entryPoint: .
          channelId: live
          firebaseToolsVersion: "13.16.0"   # pin a stable CLI
          # force: true                     # uncomment if you want to bypass warnings

