q# .github/workflows/deploy.yml
name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Sanity check: the static folder must exist
      - name: Confirm site/ folder
        run: |
          ls -la
          test -d site && ls -la site || (echo "Missing site/ folder" && exit 1)

      - name: Show firebase.json
        run: cat firebase.json

      - name: Show firebase.json and layout
        run: |
          pwd
          ls -la
          echo "----- firebase.json -----"
          cat firebase.json
          echo "----- tree: site/ -----"
          ls -la site || true

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase --version
          firebase deploy --only "hosting:ittakesimagination-main" \
            --project ittakesimagination-main \
            --non-interactive --force

