name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: firebase-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Show repo structure
        run: |
          pwd
          ls -la
          echo "---- site dir ----"
          ls -la site || true
          echo "---- firebase.json ----"
          cat firebase.json || true

      - name: Write Firebase service account to file
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ITI_SITE }}
        run: |
          echo "$FIREBASE_SA_JSON" > $HOME/firebase-sa.json
          # Basic sanity check: must start with {
          head -c 1 $HOME/firebase-sa.json | grep '{'

      - name: Install pinned Firebase CLI
        run: |
          npm i -g firebase-tools@13.16.0
          firebase --version

      - name: Deploy hosting (verbose)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-sa.json
        run: |
          firebase projects:list || true
          firebase use ittakesimagination-main
          firebase deploy --only hosting --project ittakesimagination-main --non-interactive --debug

